### PR TITLE
Add method to read timer cancellation

### PR DESCRIPTION
**Pull request by dabonnie**
Signed-off-by: Devin Bonnie <dbbonnie@amazon.com>

Add method to read timer cancellation
Add relevant unit tests 

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by emersonknapp — COMMENTED** [review]
This is great you should just open this against the ros2 repo

**Comment by dabonnie** [comment]
> This is great you should just open this against the ros2 repo

Thanks! Implemented this working with QoS branches, wanted to push for early review while I make sure it works a-ok with all the master branches. Still figuring out how to manage multiple workspaces.

**Comment by emersonknapp** [comment]
I just do a clean vcs workspace for each feature - grab master ros2.repos and branch relevant packages

**Comment by dabonnie** [comment]
This is ready to go. @thomas-moulard @emersonknapp  squash merge into AWS master after approval and then open a new PR against ros2/rclcpp?

**Comment by emersonknapp** [comment]
I wouldn't bother with all that - just go ahead and close this one, and open a PR against `ros2/rclcpp:master` from your feature branch `timer_cancel_state`

**Pull request closed without merging**
